---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: gazzite
# description will be included in the image's metadata
description: My custom bazzite-dx-nvidia image

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bazzite-dx-nvidia
image-version: stable # latest is also supported if you want new updates ASAP

stages:
  - name: ytd
    from: fedora:latest
    modules:
      - type: script
        scripts:
          - build-ytd.sh

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    repos:
      keys:
        - https://download.wavebox.app/static/wavebox_repo.key
      files:
        - wavebox.repo
      # - https://download.wavebox.app/stable/linux/rpm/wavebox.repo
      copr:
        - atim/starship
    install:
      packages:
        - ansible
        - bind-utils
        - chezmoi
        - crudini
        - git
        - gparted
        - kvantum
        - libappindicator
        - pam-u2f
        - pamu2fcfg
        - qemu-guest-agent
        - solaar
        - starship
        - tailscale
        - vim
        - Wavebox
        - yakuake
        - zsh
    remove:
      packages:
        # example: removing firefox (in favor of the flatpak)
        # "firefox" is the main package, "firefox-langpacks" is a dependency
        - firefox
        - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: bling # configure what to pull in from ublue-os/bling
    install:
      - 1password # install 1Password (stable) and `op` CLI tool

  - type: script
    scripts:
      - setup-pam-u2f.sh

  - type: copy
    from: ytd
    src: /out/ytd/bin
    dest: /usr/bin/

  - type: copy
    from: ytd
    src: /out/ytd/systemd
    dest: /usr/lib/systemd/user/

  # - type: script
  #   snippets:
  #     - chmod +x /usr/bin/yubikey-touch-detector

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
